#pragma checksum "C:\Projects\SEPUNI\CordEstates\Views\Home\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "d84eae1d8de9e2c05e00381c3751b0e61285cb06"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Home_Index), @"mvc.1.0.view", @"/Views/Home/Index.cshtml")]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "C:\Projects\SEPUNI\CordEstates\Views\_ViewImports.cshtml"
using CordEstates;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\Projects\SEPUNI\CordEstates\Views\_ViewImports.cshtml"
using CordEstates.Models;

#line default
#line hidden
#nullable disable
#nullable restore
#line 3 "C:\Projects\SEPUNI\CordEstates\Views\_ViewImports.cshtml"
using CordEstates.Models.DTOs;

#line default
#line hidden
#nullable disable
#nullable restore
#line 4 "C:\Projects\SEPUNI\CordEstates\Views\_ViewImports.cshtml"
using CordEstates.Models.ViewModels;

#line default
#line hidden
#nullable disable
#nullable restore
#line 5 "C:\Projects\SEPUNI\CordEstates\Views\_ViewImports.cshtml"
using CordEstates.Models.Enums;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"d84eae1d8de9e2c05e00381c3751b0e61285cb06", @"/Views/Home/Index.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"4d9e45a6d6d4ad71f483a51b35057b5ea157c0fe", @"/Views/_ViewImports.cshtml")]
    public class Views_Home_Index : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<LandingPageViewModel>
    {
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_0 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-controller", "Event", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_1 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-action", "Index", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_2 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("class", new global::Microsoft.AspNetCore.Html.HtmlString("btn btn-primary"), global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        private static readonly global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute __tagHelperAttribute_3 = new global::Microsoft.AspNetCore.Razor.TagHelpers.TagHelperAttribute("asp-controller", "Service", global::Microsoft.AspNetCore.Razor.TagHelpers.HtmlAttributeValueStyle.DoubleQuotes);
        #line hidden
        #pragma warning disable 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        #pragma warning restore 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#nullable restore
#line 2 "C:\Projects\SEPUNI\CordEstates\Views\Home\Index.cshtml"
  
    ViewData["Title"] = "Home";


#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n\r\n");
            DefineSection("Header", async() => {
                WriteLiteral("\r\n    <div");
                BeginWriteAttribute("class", " class=\"", 101, "\"", 109, 0);
                EndWriteAttribute();
                WriteLiteral("></div>\r\n    <header>\r\n        <div id=\"carouselExampleIndicators\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
                WriteLiteral("            <div class=\"carousel-inner\" role=\"listbox\">\r\n\r\n                    <div class=\"carousel-item active\"");
                BeginWriteAttribute("style", " style=\"", 677, "\"", 735, 4);
                WriteAttributeValue("", 685, "background-image:", 685, 17, true);
                WriteAttributeValue(" ", 702, "url(", 703, 5, true);
#nullable restore
#line 19 "C:\Projects\SEPUNI\CordEstates\Views\Home\Index.cshtml"
WriteAttributeValue("", 707, Model.Listings[0].ImageUrl, 707, 27, false);

#line default
#line hidden
#nullable disable
                WriteAttributeValue("", 734, ")", 734, 1, true);
                EndWriteAttribute();
                WriteLiteral(">\r\n                        <div class=\"carousel-caption d-none d-md-block\">\r\n                            <h3>");
#nullable restore
#line 21 "C:\Projects\SEPUNI\CordEstates\Views\Home\Index.cshtml"
                           Write(Model.Listings[0].Price);

#line default
#line hidden
#nullable disable
                WriteLiteral("</h3>\r\n                            <p>");
#nullable restore
#line 22 "C:\Projects\SEPUNI\CordEstates\Views\Home\Index.cshtml"
                          Write(Model.Listings[0].Description.Substring(0, 50));

#line default
#line hidden
#nullable disable
                WriteLiteral("</p>\r\n                        </div>\r\n                    </div>\r\n               \r\n            </div>\r\n");
                WriteLiteral("        </div>\r\n    </header>\r\n\r\n\r\n");
            }
            );
            WriteLiteral(@"
<div class=""container"">
    <div class=""row justify-content-center "">
        <h2 class=""my-2"">Upcoming Event</h2>
    </div>
    <div class=""row justify-content-center"">
        <div class=""card col-lg-12 "">
            <div class=""row"">
                <div class=""col-lg-3 m-3"" >
                    <img");
            BeginWriteAttribute("src", " src=\"", 1954, "\"", 1989, 1);
#nullable restore
#line 49 "C:\Projects\SEPUNI\CordEstates\Views\Home\Index.cshtml"
WriteAttributeValue("", 1960, Model.Events.Photo.ImageLink, 1960, 29, false);

#line default
#line hidden
#nullable disable
            EndWriteAttribute();
            WriteLiteral(" width=\"100%\"  />\r\n                </div>\r\n                <div class=\"col-lg-8\">\r\n                    <div class=\"card-body\">\r\n                        <p class=\"card-text\">");
#nullable restore
#line 53 "C:\Projects\SEPUNI\CordEstates\Views\Home\Index.cshtml"
                                        Write(Model.Events.Details);

#line default
#line hidden
#nullable disable
            WriteLiteral("</p>\r\n                    </div>\r\n                </div>\r\n            </div>\r\n            <div class=\"card-footer \">\r\n                ");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("a", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "d84eae1d8de9e2c05e00381c3751b0e61285cb068226", async() => {
                WriteLiteral("Learn More");
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Controller = (string)__tagHelperAttribute_0.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_0);
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Action = (string)__tagHelperAttribute_1.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_1);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_2);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n\r\n\r\n    <div class=\"row \">\r\n        <div class=\"row justify-content-center\">\r\n            <h2 class=\"my-2 \">Our Services</h2>\r\n            <div class=\"row md mb-2\">\r\n");
#nullable restore
#line 68 "C:\Projects\SEPUNI\CordEstates\Views\Home\Index.cshtml"
                 foreach (var service in Model.Services)
                {

#line default
#line hidden
#nullable disable
            WriteLiteral("                    <div class=\"col-md-4\">\r\n                        <div class=\"card h-100\">\r\n                            <h4 class=\"card-header\">");
#nullable restore
#line 72 "C:\Projects\SEPUNI\CordEstates\Views\Home\Index.cshtml"
                                               Write(service.ServiceName);

#line default
#line hidden
#nullable disable
            WriteLiteral("</h4>\r\n                            <div class=\"card-body\">\r\n                                <p class=\"card-text\">");
#nullable restore
#line 74 "C:\Projects\SEPUNI\CordEstates\Views\Home\Index.cshtml"
                                                Write(service.Description);

#line default
#line hidden
#nullable disable
            WriteLiteral("</p>\r\n                            </div>\r\n                            <div class=\"card-footer\">\r\n                                ");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("a", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "d84eae1d8de9e2c05e00381c3751b0e61285cb0611059", async() => {
                WriteLiteral("Learn More");
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.AnchorTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Action = (string)__tagHelperAttribute_1.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_1);
            __Microsoft_AspNetCore_Mvc_TagHelpers_AnchorTagHelper.Controller = (string)__tagHelperAttribute_3.Value;
            __tagHelperExecutionContext.AddTagHelperAttribute(__tagHelperAttribute_3);
            __tagHelperExecutionContext.AddHtmlAttribute(__tagHelperAttribute_2);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n                    </div>\r\n");
#nullable restore
#line 81 "C:\Projects\SEPUNI\CordEstates\Views\Home\Index.cshtml"
                }

#line default
#line hidden
#nullable disable
            WriteLiteral("            </div>\r\n        </div>\r\n    </div>\r\n</div>");
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<LandingPageViewModel> Html { get; private set; }
    }
}
#pragma warning restore 1591
